# These are supported funding model platforms

github: # Replace with your GitHub username or organization name (e.g., [computesdk])
  - computesdk
custom: # Replace with your own custom sponsorship URLs
  - https://buy.stripe.com/3cIdR2aJ58r5eNA8Su5AQ01
